name = "tina-cloudinary-handler"
main = "src/worker.js"
compatibility_date = "2024-02-16"

[vars]
# Anda akan mengisi ini nanti melalui dashboard Cloudflare atau command line
# CLOUDINARY_CLOUD_NAME = ""
# CLOUDINARY_API_KEY = ""
# CLOUDINARY_API_SECRET = ""
